### ISSUE TITLE
Questions about the results using wasserstein distance

### ISSUE THREAD

**Issue by XiangQiu42** [AI-secure/G-PATE#2]
Dear Author,

I notice that on your experiments, you use the original GAN and get good results.

Recently, I tried to use the wasserstein distance to train G-PATE (same hype-parameters seetings with original GAN), but it fails (about 10% accuracy on mnist classification).

To me, it's a confusion since WGAN can be seen as a improvement of the original GAN.

I wonder have you tried the wassestein distance and get similar good results like with the original GAN ?
      -If yes,  could you please share your hype-parameters seetings ?
      -If Not, Do you have any suggestions why WGAN  fails in G-PATE?

Thanks

**Comment by boxin-wbx** [comment]
Hi, we haven't tried using WGAN and do not have much experience with WGAN. But it probably needs more hyper-parameter tuning as GAN is known hard to train.
