### ISSUE TITLE
About Tensorflow

### ISSUE THREAD

**Issue by 7unahan** [AI-secure/G-PATE#3]
Hello,

Thank you for this great work. I tried on TF2 but gave me many errors, is there any guide for using TF2?

**Comment by boxin-wbx** [comment]
Hi,

Thanks for your interest in our work. 

We currently do not plan to migrate to TF2 due to the huge differences between TF1 and TF2. 

Please let us know if you have any issues with TF1. Thanks.

Best,
Boxin
